name: attendance_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

